// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Module.GameModule.Persistence;

#nullable disable

namespace Module.GameModule.Persistence.Migrations
{
    [DbContext(typeof(RouletteWheelDbContext))]
    partial class RouletteWheelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("RouletteWheel")
                .HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Module.GameModule.Entities.RouletteWheelSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PocketColor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectedNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RouletteWheelSessions", "RouletteWheel");
                });

            modelBuilder.Entity("Module.GameModule.Entities.SessionBet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("BetType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RouletteSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedBet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WinAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RouletteSessionId");

                    b.ToTable("SessionBets", "RouletteWheel");
                });

            modelBuilder.Entity("Module.GameModule.Entities.SessionBet", b =>
                {
                    b.HasOne("Module.GameModule.Entities.RouletteWheelSession", "RouletteWheelSession")
                        .WithMany("SessionBets")
                        .HasForeignKey("RouletteSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RouletteWheelSession");
                });

            modelBuilder.Entity("Module.GameModule.Entities.RouletteWheelSession", b =>
                {
                    b.Navigation("SessionBets");
                });
#pragma warning restore 612, 618
        }
    }
}
